Iter13
rusinov-artem/metrics pull request #13
Opened 2024-07-15 19:35 UTC by rusinov-artem

2024-07-17 14:07 UTC, capsulated requested changes
Написал всё в комментариях. 

И не найду чтение сигналов системы и закрытие подключения к базе, при остановки сервиса. Это нужно в `cmd` делать (либо `app`). Можно посмотреть в материалах последнего вебинара

2024-07-17 14:07 UTC, capsulated commented on server/router/router.go
> +func (t *Router) RegisterPing(h http.HandlerFunc) {
Очень неудобные и громоздкие конструкции для регистрации роутов. Я уже писал об этом, повторюсь, лучше хендлеры регистрировать в конструкторе роутера, все сразу. Не вижу профита в отдельных методах с одной строкой в каждом - только лишний код и доп сложности при масштабировании

2024-07-17 14:07 UTC, capsulated commented on server/storage/pgx_storage.go
> +func do(ctx context.Context, fn func() error) error {
Для образовательных целей - ок, но в реальных проектах не встречал ни разу ретраи к своей же базе. Обычно они используются к разным облачным saas сервисам, либо к сторонним API. В рамках курса вполне достаточно в одном месте (в файлах или в каком-то http запросе реализовать). Решай сам, оставлять или удалять

2024-07-17 14:07 UTC, capsulated commented on test/env_manager.go
> +type EnvManager struct {
А это что за объект такой? Не разу понятно, зачем он

2024-07-17 16:53 UTC, rusinov-artem commented on server/handler/update.go
> +func (h *Handler) updateSingleMetric(ctx context.Context, m *dto.Metrics) error {
К сожалению используется в двух местах (

2024-07-17 16:54 UTC, rusinov-artem commented on server/handler/updates.go
> +		err := h.updateSingleMetric(r.Context(), &(*m)[i])
Эх, надеялся не придерешься) Поправлю

2024-07-17 16:54 UTC, rusinov-artem commented on server/router/router.go
> +func (t *Router) RegisterPing(h http.HandlerFunc) {
Не вижу никаких сложностей )

2024-07-17 16:55 UTC, rusinov-artem commented on server/storage/pgx_storage.go
> +func do(ctx context.Context, fn func() error) error {
В задании было написано про ретраи похода в БД )
Так иначе не делал бы вовсе )

2024-07-17 16:56 UTC, rusinov-artem commented on test/env_manager.go
> +type EnvManager struct {
У меня где-то в тестах используются env. 
он задает env, а потом возвращает обратно тот, что был в системе )

2024-07-17 16:58 UTC, rusinov-artem commented on cmd/server/main.go
> +	db := stdlib.OpenDBFromPool(pool)
Предлагаю договориться обосновывать такие замечания. 
Мне не понятно почему этого здесь быть не должно.

2024-07-17 16:58 UTC, rusinov-artem commented on cmd/server/main.go
> +		dbpool, err = pgxpool.New(context.Background(), cfg.DatabaseDsn)
Зачем?

2024-07-29 15:21 UTC, Perederey approved these changes
Привет! Ты проделал хорошую работу, но есть несколько моментов, которые стоит улучшить:
- Обрати внимание на обработку ошибок и использование более бест-практим подходов в Go
- Поработай над именованием переменных и методов для улучшения читаемости кода
- Рассмотри возможность разделения ответственности между компонентами для улучшения архитектуры

Твой код уже работает, что здорово! Продолжай в том же духе и не забывай о постоянном улучшении и оптимизации 🔥

2024-07-29 15:21 UTC, Perederey commented on server/handler/updates.go
> +		var internalError serverError.Internal
Используй функцию errors.Is() вместо errors.As() для проверки конкретных типов ошибок, если тебе не нужна информация об ошибке

2024-07-29 15:21 UTC, Perederey commented on server/handler/handler.go
>  type Handler struct {
Рассмотри возможность разделения Handler на отдельные обработчики для каждого типа метрики для улучшения Single Responsibility Principle

2024-07-29 15:21 UTC, Perederey commented on server/handler/handler.go
>  	return h
Переименуй метод RegisterIn в Register для более краткого и понятного названия

2024-07-29 15:21 UTC, Perederey commented on server/migration/migration.go
> +func Migrate(log *zap.Logger, pool *pgxpool.Pool) {
Переименуй функцию Migrate в ApplyMigrations для более точного описания ее действия, тут я конечно придираюсь 😅

2024-07-29 15:21 UTC, Perederey commented on test/env_manager.go
> +func (t *EnvManager) Set(key, value string) {
Переименуй метод Set в SetEnv для более явного указания на работу с переменными окружения, но опять же я тут придираюсь

2024-07-29 15:21 UTC, Perederey commented on server/handler/update.go
> +	err := h.updateSingleMetric(m)
Можно упростить обработку ошибок, используя switch. Вот пример:
```go
switch {
case errors.As(err, &invalidRequest):
    http.Error(w, invalidRequest.Error(), http.StatusBadRequest)
    return
case errors.As(err, &internal):
    http.Error(w, internal.Error(), http.StatusInternalServerError)
    return
}
```

2024-07-29 15:21 UTC, Perederey commented on server/handler/updates.go
> +	if err := d.Decode(m); err != nil {
Можно в одну строку, вот так 
```go
if err := json.NewDecoder(r.Body).Decode(m); err != nil {
    http.Error(w, fmt.Sprintf("Ошибка декодирования JSON: %v", err), http.StatusBadRequest)
    return
}
```

2024-07-29 15:21 UTC, Perederey commented on server/storage/pgx_storage.go
> +		retry.DelayType(func(n uint, err error, config *retry.Config) time.Duration {
Тут ты немного перемудрили, функцию do можно упростить, используя slice для определения задержек. Типа такого:
```go
delays := []time.Duration{time.Second, 3 * time.Second, 5 * time.Second, 10 * time.Second}
retry.DelayType(func(n uint, err error, config *retry.Config) time.Duration {
    if int(n) <= len(delays) {
        return delays[n-1]
    }
    return delays[len(delays)-1]
}),
```

2024-07-29 15:21 UTC, Perederey commented on server/router/router.go
>  func (t *Router) RegisterMetricsUpdate(h http.HandlerFunc) {
проще все функции объявить в одном месте, так будет нагляднее, так сказать используй функциональный подход

2024-07-29 15:21 UTC, Perederey commented on server/router/router.go
> +func (t *Router) RegisterPing(h http.HandlerFunc) {
Вот я выше тоже про это написал, тут согласен с предыдущим ментором. Но дело за тобой

2024-07-29 15:21 UTC, Perederey commented on server/storage/pgx_storage.go
> +func do(ctx context.Context, fn func() error) error {
Встречал... но в очень плохих проектах... :(

2024-07-29 17:33 UTC, merged