Iter5
rusinov-artem/metrics pull request #5
Opened 2024-06-10 20:21 UTC by rusinov-artem

2024-06-14 12:14 UTC, capsulated requested changes
Написал комментарии

2024-06-14 12:14 UTC, capsulated commented on cmd/agent/cmd_test.go
Тест для cmd скорее избыточен. А для флагов/переменных окружения лучше создать отдельный пакет для конфига и его тестировать. Это можно в следующем инкременте

2024-06-14 12:14 UTC, capsulated commented on cmd/agent/main.go
> +type config struct {
Конфиг лучше в отдельный пакет

2024-06-14 12:14 UTC, capsulated commented on cmd/agent/main.go
> +func NewAgent() *cobra.Command {
corba  как раз тоже переместить в пакет конфига

2024-06-14 12:14 UTC, capsulated commented on cmd/server/main.go
> +func NewServerCmd() *cobra.Command {
Лучше не описывать конструкторы в cmd. А этот конструктор явно относиться к функционалу конфига

2024-06-15 09:16 UTC, rusinov-artem commented on server/handler.go
> +func NewHandler() http.Handler {
Это был лишний файл

2024-06-15 10:54 UTC, rusinov-artem commented on agent/client/client.go
> +package client
Например? В сервере чтобы он сам в себя стучался?

2024-06-15 11:00 UTC, rusinov-artem commented on server/router/router.go
> +	return t.mux
Нет. Вся идея этой структуры, что она привязывает хендлеры и URL.Path. И в итоге получается mux с ожидаемыми обработчиками привязанными к нужному url.

2024-06-15 11:01 UTC, rusinov-artem commented on test/utils.go
> +func NewProxy() *WriteProxy {
А зачем вы собственно интересуетесь?

2024-06-15 11:03 UTC, rusinov-artem commented on test/utils.go
> +func NewProxy() *WriteProxy {
Чтобы понять зачем что-то нужно в коде обычно смотрят на то где оно используется.

2024-06-15 13:10 UTC, rusinov-artem commented on cmd/agent/cmd_test.go
Тут не понял. Такого не бывает. 
Сначала пишется падающий тест, который "вынуждает" написать код, который заставит тест "проходить". 
Без этого теста не было бы параметров и конфига

2024-06-17 15:00 UTC, capsulated requested changes
Я немного запутался в ревью, несколько файлов были с пометкой 'Изменено с последнего просмотра'. Может быть, в процессе ревью были какие-то изменения?

В любом случае, можешь написать мне в пачке, и я можно назначить доп 1-1, если есть спроные или непонятные комментарии в этом ревью - голосом с шарингом экрана намного быстрее получится объяснить

2024-06-18 18:43 UTC, rusinov-artem commented on test/writer/finder.go
> +type Finder struct {
Убрал эту непонятную ерунду :D

2024-06-19 13:04 UTC, capsulated approved these changes
Всё обсудили на 1-1. 

Добавил два коммента совсем незначительных. Одно единственное замечание по странному типу, который является функцией и не используется. Удалить его просто на следующем спринте (или использовать) и будет супер.

Апрвувлю

2024-06-19 13:04 UTC, capsulated commented on server/handler/update_metrics.go
> +type MetricsProvider func() MetricsStorage
Странный тип) Скачал я в итоге проект, и посмотрел, что тип нигде и не используется. Сотри его пожалуйста, а то он очень непонятный)

2024-06-19 13:04 UTC, capsulated commented on server/handler/update_metrics.go
> +type MetricsStorage interface {
Ааа, это имя вроде хотели переименовать. Кстати, в ТЗ к инкрементам есть предложенные имена для пакетов

2024-06-22 20:07 UTC, merged